import { HttpStatus } from '@nestjs/common';

export enum errorsEnum {
  USER_NOT_FOUND = HttpStatus.NOT_FOUND,
  UNAUTHORIZED = HttpStatus.UNAUTHORIZED,
  BAD_REQUEST = HttpStatus.BAD_REQUEST,
  FORBIDDEN = HttpStatus.FORBIDDEN,
  NOT_FOUND = HttpStatus.NOT_FOUND,
  NO_RESPONSE_FROM_HTTP_REQUEST = HttpStatus.INTERNAL_SERVER_ERROR,
  ERROR_RESPONSE_FROM_HTTP_REQUEST = HttpStatus.INTERNAL_SERVER_ERROR,
  CONFLICT = HttpStatus.CONFLICT,
  DATABASE_SAVE_ERROR = HttpStatus.INTERNAL_SERVER_ERROR,
}
